{% set version = "0.8.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-av
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/av_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/av/av_{{ version }}.tar.gz
  sha256: 32358ab1e187ce4e212c26245523981b4212fefdab82187a4c39e8027c4c0922

build:
  merge_build_host: true  # [win]
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - ffmpeg
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - ffmpeg

test:
  commands:
    - $R -e "library('av')"           # [not win]
    - "\"%R%\" -e \"library('av')\""  # [win]

about:
  home: https://docs.ropensci.org/av/ (website), https://github.com/ropensci/av (devel)
  license: MIT
  summary: Bindings to 'FFmpeg' <http://www.ffmpeg.org/> AV library for working with audio and video in R. Generates high quality video from images or R graphics with custom audio. Also offers high performance tools for reading raw audio, creating 'spectrograms', and converting between countless audio / video formats. This
    package interfaces directly to the C API and does not require any command line utilities.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
